### ISSUE TITLE
Can it output this data by myself or by Sync or by itself? If it can, how to do this?

### ISSUE THREAD

**Issue by Someone999** [OsuSync/OsuRTDataProvider-Release#3]

**Comment by KedamaOvO** [comment]
This plugin does not provide any direct output.
If you want to get data, you need to write a Sync plugin, or get data via HTTP([OsuDataDistributeRestful](https://github.com/OsuSync/OsuDataDistributeRestful)).

**Comment by Someone999** [comment]
By the way , when I execute rtpp and ortdp will shows "Command execution failed",how to deal with it?

**Comment by Someone999** [comment]
and after I execute config , tips an exception:"“ConfigGUI.ConfigWindow”的类型初始值设定项引发异常。"

**Comment by Someone999** [comment]
and if it's failed when disappears this
![isitfailed](https://user-images.githubusercontent.com/45456778/55279756-10c33700-5357-11e9-8f23-522e9f4c1d52.jpg)

**Comment by Someone999** [comment]
That Window is my program

**Comment by KedamaOvO** [comment]
Try to update the ConfigGUI, which may be a bug in the low version.

**Comment by KedamaOvO** [comment]
> By the way , when I execute rtpp and ortdp will shows "Command execution failed",how to deal with it?

Both rtpp and ortdp commands are used for debug. The command format is:
rtpp [add|remove] output-method
ortdp debug [true|false]

**Comment by Someone999** [comment]
updated with "plugin update", but the same issue happens again

**Comment by Someone999** [comment]
[2:21:50] “ConfigGUI.ConfigWindow”的类型初始值设定项引发异常。
[2:21:50]    在 ConfigGUI.ConfigWindow..ctor(ConfigurationItemFactory itemFactory)
   在 ConfigGUI.ConfigGuiPlugin.<>c__DisplayClass7_0.<OnEnable>b__3()
   在 System.Windows.Threading.DispatcherOperation.InvokeDelegateCore()
   在 System.Windows.Threading.DispatcherOperation.InvokeImpl()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Windows.Threading.DispatcherOperation.Wait(TimeSpan timeout)
   在 System.Windows.Threading.Dispatcher.InvokeImpl(DispatcherOperation operation, CancellationToken cancellationToken, TimeSpan timeout)
   在 System.Windows.Threading.Dispatcher.Invoke(Action callback, DispatcherPriority priority, CancellationToken cancellationToken, TimeSpan timeout)
   在 System.Windows.Threading.Dispatcher.Invoke(Action callback)
   在 ConfigGUI.ConfigGuiPlugin.<>c__DisplayClass7_0.<OnEnable>b__2(Arguments args)
   在 Sync.Command.CommandDispatch.invoke(String name, Arguments args)
All the Information

**Comment by KedamaOvO** [comment]
Is the Sync version 2.18.2?

**Comment by Someone999** [comment]
yes,OS is Windows 10 1809

**Comment by Someone999** [comment]
![image](https://user-images.githubusercontent.com/45456778/55280179-c6dd4f80-535c-11e9-8ccc-050e3b76cbb6.png)

**Comment by KedamaOvO** [comment]
Can you tell me the plugins and versions you installed?

**Comment by Someone999** [comment]
I found another issue , after the update , that not really be updated.

**Comment by Someone999** [comment]
Because I run update again , that also be updated.

**Comment by KedamaOvO** [comment]
try use "plugins install configgui"

**Comment by Someone999** [comment]
The issue is not solved , after this , I deleted that , install again ,but the issue  occurs again

**Comment by Someone999** [comment]
Plugin: ConfigGUI.dll

**Comment by KedamaOvO** [comment]
It may be a problem caused by other plugins, try to keep only the ConfigGUI.

**Comment by Someone999** [comment]
it's solved , thanks , I'm finding conflicting plugin.

**Comment by Someone999** [comment]
I see . Because of other plugins. One or more plugin is(are) not up-to-date caused this.

**Comment by Someone999** [comment]
When I testing , Sync re-downloaded some plugins , and this issue doesn't occurred again.

**Comment by MikiraSora** [comment]
If you want to get data from ORTDP directly, please visit [this](https://github.com/yugecin/osu-rt-data-display/blob/master/osurtdd.listener.cs).
Normally ORTDP is just a plugin and dependenced by other Sync plugins use (such as [IngameOverlay](https://github.com/OsuSync/IngameOverlay) and [OsuLiveStatusPanel](https://github.com/OsuSync/OsuLiveStatusPanel))

**Comment by Someone999** [comment]
![image](https://user-images.githubusercontent.com/45456778/55377636-6d397880-5548-11e9-9254-d1c848ec47b7.png)

**Comment by Someone999** [comment]
if I catch it 
![image](https://user-images.githubusercontent.com/45456778/55377904-99a1c480-5549-11e9-8bed-61b358140777.png)

**Comment by Someone999** [comment]
this problem occurs when the version of ortdp is 1.4.4.0 and 1.2.3.0 , others version I have not tried yet.
