### ISSUE TITLE
Mods name

### ISSUE THREAD

**Issue by cyperdark** [OsuSync/OsuRTDataProvider-Release#5]
http://localhost:10800/api/ortdp/playing/mods
If there are no mods, then he writes in "name": "None"
Change it to NoMod
And for "shortName": "", add "shortName": "NM"

**Comment by KedamaOvO** [comment]
> If there are no mods, then he writes in "name": "None"
> Change it to NoMod

OK.


> And for "shortName": "", add "shortName": "NM"

No, This will affect the output of mods_str in OLSP.

**Comment by cyperdark** [comment]
I correctly understood that the shortname from OLSP?

**Comment by KedamaOvO** [comment]
The json output of OLSP simply wraps internal data using json.
Modifying the ShortName in the ORTDP will cause the text output of the OLSP to also change.
